spring:
  application:
    name: hello-client

server:
  port: 8073

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance: 
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


